from dataclasses import dataclass
from typing import Any, AsyncIterator, Protocol


@dataclass(frozen=True)
class RuntimeEvent:
    type: str
    payload: dict[str, Any]


class RuntimeAdapter(Protocol):
    async def probe(self) -> dict[str, Any]: ...
    async def open_session(self, workspace: str, instructions: str,
                           thread_id: str | None = None) -> str: ...
    def stream_turn(self, thread_id: str, text: str) -> AsyncIterator[RuntimeEvent]: ...
    async def respond(self, request_id: Any, result: dict) -> None: ...
    async def cancel(self) -> None: ...
    async def close(self) -> None: ...
